# From https://github.com/DeterminateSystems/nix-github-actions/blob/main/.github/workflows/nix.yml
name: Snake Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_nix:
    name: Check Snake
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Check Lint
        run: |
          nix develop --command \
            cpplint $(find . -name '*.cpp' -o -name '*.h')

      - name: Build
        run: |
          nix develop --command \
            make